language: node_js

node_js:
  - "12"
  
 script:
  - node -v
  - npx mocha tests

before_script:
  - npm install
  - cd front-end
  - npm install
  - cd ..
  - cd back-end
  - npm install
  - node server


